# https://taskfile.dev
version: "3"
env:
  LOCAL_HOST: http://localhost:4000

tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix
  run: iex --erl "-kernel shell_history enabled" --sname slink-local@rjhe --cookie slink-local-cookie -S mix phx.server
  sql: pgcli slink_dev
  mail: open $LOCAL_HOST/dev/mailbox

  reset-test-db:
    cmds:
      - MIX_ENV=test mix ecto.drop
  prel: MIX_ENV=prod mix release --overwrite

  # local release run in dev mode
  lp-test:
    dir: local-prod
    cmds:
      - pwd
  lp: task lp-stop && task lp-run -- daemon
  lp-run:
    dir: local-prod
    cmds:
      - run/prod.sh
  lp-stop:
    dir: local-prod
    cmds:
      - _build/dev/rel/slink/bin/slink stop
  lps: task lp-stop && task lp-run -- start
